[package]
name = "learning_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest    = { version = "0.12.19", features = ["json"] }
serde_json = "1.0.140"
tokio      = { version = "1.45.1", features = ["full"] }